sudo: required
dist: trusty

# Modern cpp settings from
#  http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - gcc-7
            - g++-7
            - cmake
            - cmake-data
            - git
            - build-essential
            - checkinstall
            - pkg-config
            - yasm
            - gfortran
            - software-properties-common
            - libjpeg8-dev
            - libjasper-dev
            - libpng12-dev
            - libtiff5-dev
            - libavcodec-dev
            - libavformat-dev
            - libswscale-dev
            - libdc1394-22-dev
            - libxine2-dev
            - libv4l-dev
            - libgstreamer1.0-dev
            - libgstreamer-plugins-base1.0-dev
            - libgtk2.0-dev
            - libtbb-dev
            - qt5-default
            - libatlas-base-dev
            - libfaac-dev
            - libmp3lame-dev
            - libtheora-dev
            - libvorbis-dev
            - libxvidcore-dev
            - libopencore-amrnb-dev
            - libopencore-amrwb-dev
            - libavresample-dev
            - x264 
            - v4l-utils
      env: COMPILER=g++-7
#For OpenCV installation
before_script:
 # Install dependencies  
  - sudo chmod +x dependencies.sh
  - ./dependencies.sh
before_install:
  - pip install --user cpp-coveralls
  - sudo -H pip install --upgrade requests[security] 
install:
  - sudo apt-get install -y -qq lcov
script:
  - bash requirements.sh
  - export CXX=$COMPILER;
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - cd /usr/local/include/opencv4/opencv2/
  - ls
  - cd /usr/include/opencv2/
  - ls
  - make code_coverage
  - test/cpp-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
