sudo: required
dist: trusty

# Modern cpp settings from
#  http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - gcc-7
            - g++-7
            - cmake
            - cmake-data
            - git
            - build-essential
            - checkinstall
            - pkg-config
            - yasm
            - gfortran
            - software-properties-common
            - libjpeg8-dev
            - libjasper-dev
            - libpng12-dev
            - libtiff5-dev
            - libavcodec-dev
            - libavformat-dev
            - libswscale-dev
            - libdc1394-22-dev
            - libxine2-dev
            - libv4l-dev
            - libgstreamer1.0-dev
            - libgstreamer-plugins-base1.0-dev
            - libgtk2.0-dev
            - libtbb-dev
            - qt5-default
            - libatlas-base-dev
            - libfaac-dev
            - libmp3lame-dev
            - libtheora-dev
            - libvorbis-dev
            - libxvidcore-dev
            - libopencore-amrnb-dev
            - libopencore-amrwb-dev
            - libavresample-dev
            - x264 
            - v4l-utils
      env: COMPILER=g++-7
#For OpenCV installation
before_script:
  - sudo apt-get install -y build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  - sudo apt-get install -y python2.7-dev python3-dev python-dev python-numpy python3-numpy
  - sudo apt-get install -y libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev
  - sudo apt-get install -y libv4l-dev v4l-utils qv4l2 v4l2ucp
  - sudo apt-get install -y curl


  - echo "** Download opencv-4.3.0"

  - curl -L https://github.com/opencv/opencv/archive/4.4.0.zip -o opencv-4.4.0.zip
  - curl -L https://github.com/opencv/opencv_contrib/archive/4.4.0.zip -o opencv_contrib-4.4.0.zip
  - unzip opencv-4.4.0.zip
  - unzip opencv_contrib-4.4.0.zip
  - cd opencv-4.4.0/


  - echo "** Apply patch"
  - sed -i 's/include <Eigen\/Core>/include <eigen3\/Eigen\/Core>/g' modules/core/include/opencv2/core/private.hpp
  - sed -i 's/{CUDNN_INCLUDE_DIR}\/cudnn.h/{CUDNN_INCLUDE_DIR}\/cudnn_version.h/g' cmake/FindCUDNN.cmake


  - echo "** Building..."
  - mkdir release
  - cd release/
  - cmake -D WITH_CUDA=ON -D WITH_CUDNN=OFF -D CUDA_ARCH_BIN="5.3,6.2,7.2" -D CUDA_ARCH_PTX="" -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.4.0/modules -D WITH_GSTREAMER=ON -D WITH_LIBV4L=ON -D BUILD_opencv_python2=ON -D BUILD_opencv_python3=ON -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_EXAMPLES=OFF -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j$(nproc)
  - sudo make install
  - sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf.d/opencv.conf"
  - sudo ldconfig

  - cd ../../
  - echo "OpenCV installation DONE!"
before_install:
  - pip install --user cpp-coveralls
  - sudo -H pip install --upgrade requests[security] 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install -y -qq lcov
script:
  - bash requirements.sh
  - export CXX=$COMPILER;
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - make code_coverage
  - test/cpp-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
